/**********************************************************************************************
 * Filename:       Link_Loss.h
 *
 * Description:    This file contains the Link_Loss service definitions and
 *                 prototypes.
 *
 *                 Generated by:
 *                 BDS version: 1.0.2116.0
 *                 Plugin:      Texas Instruments CC26xx BLE SDK v2.1 GATT Server plugin 1.0.5 beta
 *                 Time:        Mon Jun 13 2016 10:49:18 GMT+03:00
 *

 * Copyright (c) 2015, Texas Instruments Incorporated
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 * *  Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *
 * *  Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 *
 * *  Neither the name of Texas Instruments Incorporated nor the names of
 *    its contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO,
 * THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
 * PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR
 * CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
 * EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
 * PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
 * OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
 * WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
 * OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,
 * EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 *************************************************************************************************/

#ifndef _LINK_LOSS_H_
#define _LINK_LOSS_H_

#ifdef __cplusplus
extern "C"
{
#endif

/*********************************************************************
 * INCLUDES
 */

/*********************************************************************
 * CONSTANTS
 */

/*********************************************************************
* CONSTANTS
*/
// Service UUID
#define LINK_LOSS_SERV_UUID 0x1803

// Alert Level Characteristic defines
#define LL_ALERT_LEVEL_ID                 0
#define LL_ALERT_LEVEL_UUID               0x2A06
#define LL_ALERT_LEVEL_LEN                1
#define LL_ALERT_LEVEL_LEN_MIN            1

/*********************************************************************
 * TYPEDEFS
 */
//
// Fields in characteristic "Alert Level"
//   Field "Alert_Level" format: uint8, bits: 8
//     Enumerations for Alert_Level
//       No Alert -- 0
//       Mild Alert -- 1
//       High Alert -- 2

/*********************************************************************
 * MACROS
 */

/*********************************************************************
 * Profile Callbacks
 */

// Callback when a characteristic value has changed
typedef void (*LinkLossChange_t)( uint8_t paramID );

typedef struct
{
  LinkLossChange_t        pfnChangeCb;  // Called when characteristic value changes
} LinkLossCBs_t;



/*********************************************************************
 * API FUNCTIONS 
 */


/*
 * LinkLoss_AddService- Initializes the LinkLoss service by registering
 *          GATT attributes with the GATT server.
 *
 */
extern bStatus_t LinkLoss_AddService( void );

/*
 * LinkLoss_RegisterAppCBs - Registers the application callback function.
 *                    Only call this function once.
 *
 *    appCallbacks - pointer to application callbacks.
 */
extern bStatus_t LinkLoss_RegisterAppCBs( LinkLossCBs_t *appCallbacks );

/*
 * LinkLoss_SetParameter - Set a LinkLoss parameter.
 *
 *    param - Profile parameter ID
 *    len   - length of data to write
 *    value - pointer to data to write.  This is dependent on
 *            the parameter ID and may be cast to the appropriate 
 *            data type (example: data type of uint16_t will be cast to 
 *            uint16_t pointer).
 */
extern bStatus_t LinkLoss_SetParameter( uint8_t param, uint16_t len, void *value );
  
/*
 * LinkLoss_GetParameter - Get a LinkLoss parameter.
 *
 *    param - Profile parameter ID
 *    len   - pointer to a variable that contains the maximum length that can be written to *value.
              After the call, this value will contain the actual returned length.
 *    value - pointer to data to write.  This is dependent on
 *            the parameter ID and may be cast to the appropriate 
 *            data type (example: data type of uint16_t will be cast to 
 *            uint16_t pointer).
 */
extern bStatus_t LinkLoss_GetParameter( uint8_t param, uint16_t *len, void *value );

/*********************************************************************
*********************************************************************/

#ifdef __cplusplus
}
#endif

#endif /* _LINK_LOSS_H_ */
